# This is a basic workflow to help you get started with Actions

name: Build docker image and publish SDK

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          git fetch --prune --tags --force

      - name: Build Docker image
        run: |
          make build JOBS=
      - name: Export SDK
        run: |
          make run
          make sdk

      - name: Print diagnostic info
        run: |
          pwd
          ls -l
          ls -l outdir

      - name: Share SDK
        uses: actions/upload-artifact@v2
        with:
          name: SDK
          path: outdir/*.tar.gz

      - name: Push to Docker Hub
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          eval $(make env)
          # dunno if useful, but why not to erase it?
          export HISTFILE=
          echo "${DOCKER_ACCESS_TOKEN}" | docker login -u ccfactory --password-stdin
          docker tag ${IMAGE}:${IMAGE_VERSION} ccfactory/${IMAGE}:${IMAGE_VERSION}
          docker push ccfactory/${IMAGE}:${IMAGE_VERSION}
          docker logout
      - name: Draft new Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatic secret
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            New features:
            - elaborate
            Fixed:
            - a bugfix
          draft: true
          prerelease: false
